#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/home/mohacsi/work/venv_37/lib/python3.7/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/home/mohacsi/work/venv_37/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/mohacsi/work/optimizer/optimizer/new_test_files/ca1_pc_simplification/mod_files/x86_64/.libs/libnrnmech.so" "$@"
