#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _bk_ch_reg(void);
extern void _bk_ch_pool_reg(void);
extern void _cacum_lpool_reg(void);
extern void _cacum_reg(void);
extern void _cacum_npool_reg(void);
extern void _cad_mod_for_ltp_reg(void);
extern void _cagk_npool_reg(void);
extern void _CaL_reg(void);
extern void _CaL_pool2_reg(void);
extern void _CaN_BG_pool2_reg(void);
extern void _CaN_BG_pool_reg(void);
extern void _CaN_reg(void);
extern void _CaR_reg(void);
extern void _CaT_reg(void);
extern void _H_CA1pyr_dist_reg(void);
extern void _H_CA1pyr_prox_reg(void);
extern void _K_A_dist_reg(void);
extern void _K_AHP3_lpool_reg(void);
extern void _K_AHP3_reg(void);
extern void _K_A_prox_reg(void);
extern void _K_C_1D_reg(void);
extern void _K_C_1D_npool_reg(void);
extern void _kd2_reg(void);
extern void _kd_params3_reg(void);
extern void _K_DRS4_reg(void);
extern void _K_DRS4_params_reg(void);
extern void _K_DRS4_params_voltage_dep_reg(void);
extern void _K_M2_reg(void);
extern void _K_M2_params_reg(void);
extern void _km_reg(void);
extern void _K_M_reg(void);
extern void _km_q10_2_reg(void);
extern void _Leak_pyr_reg(void);
extern void _rsg_reg(void);
extern void _vecevent_reg(void);
extern void _vmax_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," \"bk_ch.mod\"");
    fprintf(stderr," \"bk_ch_pool.mod\"");
    fprintf(stderr," \"cacum_lpool.mod\"");
    fprintf(stderr," \"cacum.mod\"");
    fprintf(stderr," \"cacum_npool.mod\"");
    fprintf(stderr," \"cad_mod_for_ltp.mod\"");
    fprintf(stderr," \"cagk_npool.mod\"");
    fprintf(stderr," \"CaL.mod\"");
    fprintf(stderr," \"CaL_pool2.mod\"");
    fprintf(stderr," \"CaN_BG_pool2.mod\"");
    fprintf(stderr," \"CaN_BG_pool.mod\"");
    fprintf(stderr," \"CaN.mod\"");
    fprintf(stderr," \"CaR.mod\"");
    fprintf(stderr," \"CaT.mod\"");
    fprintf(stderr," \"H_CA1pyr_dist.mod\"");
    fprintf(stderr," \"H_CA1pyr_prox.mod\"");
    fprintf(stderr," \"K_A_dist.mod\"");
    fprintf(stderr," \"K_AHP3_lpool.mod\"");
    fprintf(stderr," \"K_AHP3.mod\"");
    fprintf(stderr," \"K_A_prox.mod\"");
    fprintf(stderr," \"K_C_1D.mod\"");
    fprintf(stderr," \"K_C_1D_npool.mod\"");
    fprintf(stderr," \"kd2.mod\"");
    fprintf(stderr," \"kd_params3.mod\"");
    fprintf(stderr," \"K_DRS4.mod\"");
    fprintf(stderr," \"K_DRS4_params.mod\"");
    fprintf(stderr," \"K_DRS4_params_voltage_dep.mod\"");
    fprintf(stderr," \"K_M2.mod\"");
    fprintf(stderr," \"K_M2_params.mod\"");
    fprintf(stderr," \"km.mod\"");
    fprintf(stderr," \"K_M.mod\"");
    fprintf(stderr," \"km_q10_2.mod\"");
    fprintf(stderr," \"Leak_pyr.mod\"");
    fprintf(stderr," \"rsg.mod\"");
    fprintf(stderr," \"vecevent.mod\"");
    fprintf(stderr," \"vmax.mod\"");
    fprintf(stderr, "\n");
  }
  _bk_ch_reg();
  _bk_ch_pool_reg();
  _cacum_lpool_reg();
  _cacum_reg();
  _cacum_npool_reg();
  _cad_mod_for_ltp_reg();
  _cagk_npool_reg();
  _CaL_reg();
  _CaL_pool2_reg();
  _CaN_BG_pool2_reg();
  _CaN_BG_pool_reg();
  _CaN_reg();
  _CaR_reg();
  _CaT_reg();
  _H_CA1pyr_dist_reg();
  _H_CA1pyr_prox_reg();
  _K_A_dist_reg();
  _K_AHP3_lpool_reg();
  _K_AHP3_reg();
  _K_A_prox_reg();
  _K_C_1D_reg();
  _K_C_1D_npool_reg();
  _kd2_reg();
  _kd_params3_reg();
  _K_DRS4_reg();
  _K_DRS4_params_reg();
  _K_DRS4_params_voltage_dep_reg();
  _K_M2_reg();
  _K_M2_params_reg();
  _km_reg();
  _K_M_reg();
  _km_q10_2_reg();
  _Leak_pyr_reg();
  _rsg_reg();
  _vecevent_reg();
  _vmax_reg();
}
