#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/usr/local/software/jureca/Stages/Devel-2019a/software/NEURON/7.6.5-gpsmpi-2019a-Python-3.6.8"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/usr/local/software/jureca/Stages/Devel-2019a/software/NEURON/7.6.5-gpsmpi-2019a-Python-3.6.8/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/p/home/jusers/mohacsi1/jureca/optimizer/optimizer/new_test_files/Luca_modell_python3/x86_64/.libs/libnrnmech.so" "$@"
