#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/nest/anaconda3"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/nest/anaconda3/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/nest/Desktop/optimizer/optimizer/new_test_files/Modellke/mods/x86_64/.libs/libnrnmech.so" "$@"
