COMMENT

   **************************************************
   File generated by: neuroConstruct v1.5.1 
   **************************************************

   This file holds the implementation in NEURON of the Cell Mechanism:
   Ca_conc_dend3 (Type: Ion concentration, Model: ChannelML based process)

   with parameters: 
   /channelml/@units = SI Units 
   /channelml/notes = A channel from Maex, R and De Schutter, E. Synchronization of Golgi and Granule Cell Firing in a     Detailed Network Model of the Cerebellar Granule  ... 
   /channelml/ion/@name = ca 
   /channelml/ion/@charge = 2 
   /channelml/ion/@role = SignallingSubstance 
   /channelml/ion/notes = Signifies that the ion is involved in a process which alters its concentration 
   /channelml/ion_concentration/@name = Ca_conc_dend3 
   /channelml/ion_concentration/status/@value = stable 
   /channelml/ion_concentration/status/contributor/name = Boglarka Szoke 
   /channelml/ion_concentration/notes = An expontially decaying pool of calcium 
   /channelml/ion_concentration/ion_species = ca 
   /channelml/ion_concentration/decaying_pool_model/@resting_conc = 0.0 
   /channelml/ion_concentration/decaying_pool_model/@decay_constant = 0.01333 
   /channelml/ion_concentration/decaying_pool_model/fixed_pool_info/phi = 1.246672948e+3 

// File from which this was generated: /home/kali/nC_projects/CA1_NEURON/cellMechanisms/Ca_conc_dend3/Ca_conc.xml

// XSL file with mapping to simulator: /home/kali/nC_projects/CA1_NEURON/cellMechanisms/Ca_conc_dend3/ChannelML_v1.8.1_NEURONmod.xsl

ENDCOMMENT


?  This is a NEURON mod file generated from a ChannelML file

?  Unit system of original ChannelML file: SI Units

COMMENT
    A channel from Maex, R and De Schutter, E. Synchronization of Golgi and Granule Cell Firing in a
    Detailed Network Model of the Cerebellar Granule Cell Layer.
ENDCOMMENT

    

? Creating ion concentration

TITLE Channel: Ca_conc_dend3

COMMENT
    An expontially decaying pool of calcium
ENDCOMMENT


UNITS {
    (mV) = (millivolt)
    (mA) = (milliamp)
    (um) = (micrometer)
    (l) = (liter)
    (molar) = (1/liter)
    (mM) = (millimolar)
}

    
NEURON {
    SUFFIX Ca_conc_dend3
    USEION ca READ ica WRITE cai VALENCE 2
    
    RANGE cai
    
    RANGE rest_conc
    
    
    RANGE tau
    
    
    GLOBAL total_current
    
    
    RANGE phi
    
    
}

ASSIGNED {

    ica (mA/cm2)
    diam (um)
}

INITIAL {
    cai = rest_conc

}

PARAMETER {

    total_current
    rest_conc = 0 (mM)
          
    
    tau = 13.33 (ms)
   
    phi = 1.246672948e+3
    
}

STATE {

    cai (mM)

}

BREAKPOINT {

    SOLVE conc METHOD derivimplicit
    

}

DERIVATIVE conc {
    cai' = - (phi * ica) - ((cai - rest_conc)/tau)
    

}

