python /home/mohacsi/work/optimizer/optimizer/optimizer.py -c /home/mohacsi/work/optimizer/ALLtest/optimizer_multirun/adexpif_external_ca3_pcNondominatedSortedGAPygmo_1/_settings.xml
python /home/mohacsi/work/optimizer/optimizer/optimizer.py -c /home/mohacsi/work/optimizer/ALLtest/optimizer_multirun/adexpif_external_ca3_pcNondominatedSortedGAPygmo_2/_settings.xml
python /home/mohacsi/work/optimizer/optimizer/optimizer.py -c /home/mohacsi/work/optimizer/ALLtest/optimizer_multirun/adexpif_external_ca3_pcNondominatedSortedGAPygmo_3/_settings.xml
python /home/mohacsi/work/optimizer/optimizer/optimizer.py -c /home/mohacsi/work/optimizer/ALLtest/optimizer_multirun/adexpif_external_ca3_pcNondominatedSortedGAPygmo_4/_settings.xml
python /home/mohacsi/work/optimizer/optimizer/optimizer.py -c /home/mohacsi/work/optimizer/ALLtest/optimizer_multirun/adexpif_external_ca3_pcNondominatedSortedGAPygmo_5/_settings.xml
python /home/mohacsi/work/optimizer/optimizer/optimizer.py -c /home/mohacsi/work/optimizer/ALLtest/optimizer_multirun/adexpif_external_ca3_pcNondominatedSortedGAPygmo_6/_settings.xml
python /home/mohacsi/work/optimizer/optimizer/optimizer.py -c /home/mohacsi/work/optimizer/ALLtest/optimizer_multirun/adexpif_external_ca3_pcNondominatedSortedGAPygmo_7/_settings.xml
python /home/mohacsi/work/optimizer/optimizer/optimizer.py -c /home/mohacsi/work/optimizer/ALLtest/optimizer_multirun/adexpif_external_ca3_pcNondominatedSortedGAPygmo_8/_settings.xml
python /home/mohacsi/work/optimizer/optimizer/optimizer.py -c /home/mohacsi/work/optimizer/ALLtest/optimizer_multirun/adexpif_external_ca3_pcNondominatedSortedGAPygmo_9/_settings.xml
python /home/mohacsi/work/optimizer/optimizer/optimizer.py -c /home/mohacsi/work/optimizer/ALLtest/optimizer_multirun/adexpif_external_ca3_pcNondominatedSortedGAPygmo_10/_settings.xml
