#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _bk_ch_reg(void);
extern void _bk_ch_pool_reg(void);
extern void _cacum_lpool_reg(void);
extern void _cacum_reg(void);
extern void _cacum_npool_reg(void);
extern void _cad_mod_for_ltp_reg(void);
extern void _cagk_npool_reg(void);
extern void _CaL_reg(void);
extern void _CaL_pool2_ghk_reg(void);
extern void _CaL_pool2_reg(void);
extern void _CaN_BG_pool2_ghk_reg(void);
extern void _CaN_BG_pool2_reg(void);
extern void _CaN_BG_pool_reg(void);
extern void _CaN_reg(void);
extern void _car_reg(void);
extern void _CaR_reg(void);
extern void _Ca_R_old_reg(void);
extern void _cat31_reg(void);
extern void _cat32_reg(void);
extern void _cat33_reg(void);
extern void _CaT_reg(void);
extern void _D1_LTP_time_window_Luca_cai_initials_reg(void);
extern void _H_CA1pyr_dist_reg(void);
extern void _H_CA1pyr_dist_tauconstant_reg(void);
extern void _H_CA1pyr_prox_reg(void);
extern void _H_CA1pyr_prox_tauconstant_reg(void);
extern void _K_A_dist_reg(void);
extern void _K_AHP3_lpool_reg(void);
extern void _K_AHP3_reg(void);
extern void _K_A_prox_reg(void);
extern void _kd_params3_reg(void);
extern void _K_DRS4_params_voltage_dep_reg(void);
extern void _K_M2_reg(void);
extern void _K_M2_params_reg(void);
extern void _km_reg(void);
extern void _K_M_reg(void);
extern void _km_q10_2_reg(void);
extern void _Leak_pyr_reg(void);
extern void _Na_BG_axon_reg(void);
extern void _Na_BG_dend_reg(void);
extern void _Na_BG_soma_reg(void);
extern void _NMDAb_reg(void);
extern void _nmda_dsyn_reg(void);
extern void _nmda_Grunditz_reg(void);
extern void _NMDA_JS_reg(void);
extern void _NMDA_JS_modositott_reg(void);
extern void _NMDA_Mg_T_reg(void);
extern void _NMDA_M_modositott_reg(void);
extern void _nmda_reg(void);
extern void _sKCa_reg(void);
extern void _vecevent_reg(void);
extern void _vmax_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," \"bk_ch.mod\"");
    fprintf(stderr," \"bk_ch_pool.mod\"");
    fprintf(stderr," \"cacum_lpool.mod\"");
    fprintf(stderr," \"cacum.mod\"");
    fprintf(stderr," \"cacum_npool.mod\"");
    fprintf(stderr," \"cad_mod_for_ltp.mod\"");
    fprintf(stderr," \"cagk_npool.mod\"");
    fprintf(stderr," \"CaL.mod\"");
    fprintf(stderr," \"CaL_pool2_ghk.mod\"");
    fprintf(stderr," \"CaL_pool2.mod\"");
    fprintf(stderr," \"CaN_BG_pool2_ghk.mod\"");
    fprintf(stderr," \"CaN_BG_pool2.mod\"");
    fprintf(stderr," \"CaN_BG_pool.mod\"");
    fprintf(stderr," \"CaN.mod\"");
    fprintf(stderr," \"car.mod\"");
    fprintf(stderr," \"CaR.mod\"");
    fprintf(stderr," \"Ca_R_old.mod\"");
    fprintf(stderr," \"cat31.mod\"");
    fprintf(stderr," \"cat32.mod\"");
    fprintf(stderr," \"cat33.mod\"");
    fprintf(stderr," \"CaT.mod\"");
    fprintf(stderr," \"D1_LTP_time_window_Luca_cai_initials.mod\"");
    fprintf(stderr," \"H_CA1pyr_dist.mod\"");
    fprintf(stderr," \"H_CA1pyr_dist_tauconstant.mod\"");
    fprintf(stderr," \"H_CA1pyr_prox.mod\"");
    fprintf(stderr," \"H_CA1pyr_prox_tauconstant.mod\"");
    fprintf(stderr," \"K_A_dist.mod\"");
    fprintf(stderr," \"K_AHP3_lpool.mod\"");
    fprintf(stderr," \"K_AHP3.mod\"");
    fprintf(stderr," \"K_A_prox.mod\"");
    fprintf(stderr," \"kd_params3.mod\"");
    fprintf(stderr," \"K_DRS4_params_voltage_dep.mod\"");
    fprintf(stderr," \"K_M2.mod\"");
    fprintf(stderr," \"K_M2_params.mod\"");
    fprintf(stderr," \"km.mod\"");
    fprintf(stderr," \"K_M.mod\"");
    fprintf(stderr," \"km_q10_2.mod\"");
    fprintf(stderr," \"Leak_pyr.mod\"");
    fprintf(stderr," \"Na_BG_axon.mod\"");
    fprintf(stderr," \"Na_BG_dend.mod\"");
    fprintf(stderr," \"Na_BG_soma.mod\"");
    fprintf(stderr," \"NMDAb.mod\"");
    fprintf(stderr," \"nmda_dsyn.mod\"");
    fprintf(stderr," \"nmda_Grunditz.mod\"");
    fprintf(stderr," \"NMDA_JS.mod\"");
    fprintf(stderr," \"NMDA_JS_modositott.mod\"");
    fprintf(stderr," \"NMDA_Mg_T.mod\"");
    fprintf(stderr," \"NMDA_M_modositott.mod\"");
    fprintf(stderr," \"nmda.mod\"");
    fprintf(stderr," \"sKCa.mod\"");
    fprintf(stderr," \"vecevent.mod\"");
    fprintf(stderr," \"vmax.mod\"");
    fprintf(stderr, "\n");
  }
  _bk_ch_reg();
  _bk_ch_pool_reg();
  _cacum_lpool_reg();
  _cacum_reg();
  _cacum_npool_reg();
  _cad_mod_for_ltp_reg();
  _cagk_npool_reg();
  _CaL_reg();
  _CaL_pool2_ghk_reg();
  _CaL_pool2_reg();
  _CaN_BG_pool2_ghk_reg();
  _CaN_BG_pool2_reg();
  _CaN_BG_pool_reg();
  _CaN_reg();
  _car_reg();
  _CaR_reg();
  _Ca_R_old_reg();
  _cat31_reg();
  _cat32_reg();
  _cat33_reg();
  _CaT_reg();
  _D1_LTP_time_window_Luca_cai_initials_reg();
  _H_CA1pyr_dist_reg();
  _H_CA1pyr_dist_tauconstant_reg();
  _H_CA1pyr_prox_reg();
  _H_CA1pyr_prox_tauconstant_reg();
  _K_A_dist_reg();
  _K_AHP3_lpool_reg();
  _K_AHP3_reg();
  _K_A_prox_reg();
  _kd_params3_reg();
  _K_DRS4_params_voltage_dep_reg();
  _K_M2_reg();
  _K_M2_params_reg();
  _km_reg();
  _K_M_reg();
  _km_q10_2_reg();
  _Leak_pyr_reg();
  _Na_BG_axon_reg();
  _Na_BG_dend_reg();
  _Na_BG_soma_reg();
  _NMDAb_reg();
  _nmda_dsyn_reg();
  _nmda_Grunditz_reg();
  _NMDA_JS_reg();
  _NMDA_JS_modositott_reg();
  _NMDA_Mg_T_reg();
  _NMDA_M_modositott_reg();
  _nmda_reg();
  _sKCa_reg();
  _vecevent_reg();
  _vmax_reg();
}
