
//  ******************************************************
// 
//     File generated by: neuroConstruct v1.6.0
// 
//  ******************************************************

*absolute
*cartesian
*asymmetric

*set_global	         RA 1.0  // using: Units[GENESIS_SI_specAxialResistance, symbol: ohm m]

*set_global	         CM 0.01   // using: Units[GENESIS_SI_specificCapacitance, symbol: F m-2]

*set_global	         RM	0.6666667  // using: Units[GENESIS_SI_specificMembraneResistance, symbol: ohm m²]

*set_global	         EREST_ACT	0.0  // using: Units[GENESIS_SI_voltage, symbol: V]

*set_compt_param     ELEAK	0.0  // using: Units[GENESIS_SI_voltage, symbol: V]

*compt /library/compartment

// NOTE: readcell usually assumes SI units (meters, seconds, ohms) above and lengths (below)
// in micrometers. If we use physiological units above, the lengths below will appear quite high


// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
// *set_compt_param     ELEAK -0.0594  // using: Units[GENESIS_SI_voltage, symbol: V]
// *set_compt_param     RM 0.33333334  // using: Units[GENESIS_SI_specificMembraneResistance, symbol: ohm m²]


*double_endpoint
Soma none -27.5691 -25.7019 -11.2267 5.88883 -1.92445 -11.2362 22.052 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
AxonCyan_1_R__Extra_0 Soma 6.3 -1.35 -31.65 32.76939 5.659524 -35.28204 0.6346358 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
AxonCyan_1_R__Extra_1 AxonCyan_1_R__Extra_0 59.23878 12.66905 -38.91408 0.6346358 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
AxonCyan_1_R AxonCyan_1_R__Extra_1 85.70817 19.67857 -42.54612 0.6346358 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
AxonCyan_10000__Extra_0 AxonCyan_1_R 112.1776 26.6881 -46.17815 0.4858827 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
AxonCyan_10000__Extra_1 AxonCyan_10000__Extra_0 138.6469 33.69762 -49.8102 0.4858827 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
AxonCyan_10000 AxonCyan_10000__Extra_1 165.1163 40.70715 -53.44223 0.4858827 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
AxonCyan_1_R_1 AxonCyan_10000 134.2 32.52 -49.2 150.1731 35.8688 -51.38936 0.3297164 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
AxonCyan_10301 AxonCyan_1_R_1 166.1462 39.2176 -53.57872 0.2880722 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
AxonCyan_1_R_1_1__Extra_0 AxonCyan_10301 160.1 37.95 -52.75 163.1517 52.30486 -62.96872 0.2461778 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
AxonCyan_1_R_1_1 AxonCyan_1_R_1_1__Extra_0 166.2034 66.65972 -73.18743 0.2461778 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
AxonCyan_10356__Extra_0 AxonCyan_1_R_1_1 169.2551 81.01459 -83.40614 0.2081289 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
AxonCyan_10356 AxonCyan_10356__Extra_0 172.3069 95.36945 -93.62486 0.2081289 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
AxonCyan_1_R_1_2__Extra_0 AxonCyan_10301 160.1 37.95 -52.75 170.5436 18.73536 -56.78276 0.3149617 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
AxonCyan_1_R_1_2__Extra_1 AxonCyan_1_R_1_2__Extra_0 180.9872 -0.4792824 -60.81551 0.3149617 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
AxonCyan_1_R_1_2__Extra_2 AxonCyan_1_R_1_2__Extra_1 191.4308 -19.69392 -64.84827 0.3149617 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
AxonCyan_1_R_1_2 AxonCyan_1_R_1_2__Extra_2 201.8743 -38.90857 -68.88103 0.3149617 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
AxonCyan_10484__Extra_0 AxonCyan_1_R_1_2 212.3179 -58.12321 -72.91379 0.2351574 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
AxonCyan_10484__Extra_1 AxonCyan_10484__Extra_0 222.7615 -77.33785 -76.94655 0.2351574 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
AxonCyan_10484__Extra_2 AxonCyan_10484__Extra_1 233.2051 -96.55249 -80.97931 0.2351574 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
AxonCyan_10484 AxonCyan_10484__Extra_2 243.6486 -115.7671 -85.01206 0.2351574 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
AxonCyan_1_R_2__Extra_0 AxonCyan_10000 134.2 32.52 -49.2 151.9637 10.88417 -59.22891 0.4428894 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
AxonCyan_1_R_2 AxonCyan_1_R_2__Extra_0 169.7274 -10.75166 -69.25783 0.4428894 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
AxonCyan_10804__Extra_0 AxonCyan_1_R_2 187.4911 -32.3875 -79.28674 0.3671179 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
AxonCyan_10804 AxonCyan_10804__Extra_0 205.2548 -54.02333 -89.31564 0.3671179 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
DendriteCyan_1_R Soma -8.32 3.96 -30.95 0.8191929 21.82184 -29.55115 0.4556195 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_11007 DendriteCyan_1_R 9.958385 39.68367 -28.15229 0.4086682 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
DendriteCyan_1_R_1__Extra_0 DendriteCyan_11007 6.38 32.69 -28.7 21.95305 45.45232 -30.51409 0.2308113 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_R_1__Extra_1 DendriteCyan_1_R_1__Extra_0 37.52609 58.21463 -32.32818 0.2308113 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_R_1__Extra_2 DendriteCyan_1_R_1__Extra_1 53.09914 70.97695 -34.14227 0.2308113 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_R_1 DendriteCyan_1_R_1__Extra_2 68.67219 83.73927 -35.95636 0.2308113 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_11084__Extra_0 DendriteCyan_1_R_1 84.24524 96.50159 -37.77045 0.2124286 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_11084__Extra_1 DendriteCyan_11084__Extra_0 99.81828 109.2639 -39.58455 0.2124286 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_11084__Extra_2 DendriteCyan_11084__Extra_1 115.3913 122.0262 -41.39864 0.2124286 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_11084 DendriteCyan_11084__Extra_2 130.9644 134.7885 -43.21273 0.2124286 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
DendriteCyan_1_R_2__Extra_0 DendriteCyan_11007 6.38 32.69 -28.7 6.285085 52.9713 -27.98048 0.3306505 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_R_2 DendriteCyan_1_R_2__Extra_0 6.190169 73.2526 -27.26096 0.3306505 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_11413__Extra_0 DendriteCyan_1_R_2 6.095254 93.53391 -26.54144 0.2305012 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_11413 DendriteCyan_11413__Extra_0 6.000338 113.8152 -25.82192 0.2305012 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
DendriteCyan_1_1_R Soma 7.79 -3.33 -26.75 8.569726 -2.813625 -26.75 0.74 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_11549 DendriteCyan_1_1_R 9.349453 -2.29725 -26.75 0.74 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
DendriteCyan_1_1_R_1 DendriteCyan_1_11549 9.3 -2.33 -26.75 20.13756 -9.250294 -27.17381 0.4098432 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_11553 DendriteCyan_1_1_R_1 30.97511 -16.17059 -27.59763 0.3582335 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
DendriteCyan_1_1_R_1_1__Extra_0 DendriteCyan_1_11553 27.2 -13.76 -27.45 51.34808 -13.33761 -30.05623 0.2943876 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_1_R_1_1 DendriteCyan_1_1_R_1_1__Extra_0 75.49615 -12.91522 -32.66246 0.2943876 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_11600__Extra_0 DendriteCyan_1_1_R_1_1 99.64423 -12.49283 -35.26869 0.2168029 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_11600 DendriteCyan_1_11600__Extra_0 123.7923 -12.07044 -37.87492 0.2168029 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
DendriteCyan_1_1_R_1_2__Extra_0 DendriteCyan_1_11553 27.2 -13.76 -27.45 45.74401 -25.59174 -25.66632 0.3 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_1_R_1_2 DendriteCyan_1_1_R_1_2__Extra_0 64.28802 -37.42348 -23.88264 0.3 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_11757__Extra_0 DendriteCyan_1_1_R_1_2 82.83203 -49.25522 -22.09896 0.3 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_11757 DendriteCyan_1_11757__Extra_0 101.376 -61.08696 -20.31528 0.3 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
DendriteCyan_1_1_R_2 DendriteCyan_1_11549 9.3 -2.33 -26.75 15.9228 2.240901 -25.74907 0.641368 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_11927 DendriteCyan_1_1_R_2 22.5456 6.811802 -24.74815 0.4730153 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
DendriteCyan_1_1_R_2_1__Extra_0 DendriteCyan_1_11927 21.21 5.89 -24.95 35.9553 14.97437 -24.54106 0.3 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_1_R_2_1 DendriteCyan_1_1_R_2_1__Extra_0 50.7006 24.05873 -24.13211 0.3 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_11957__Extra_0 DendriteCyan_1_1_R_2_1 65.44591 33.1431 -23.72317 0.3 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_11957 DendriteCyan_1_11957__Extra_0 80.19121 42.22747 -23.31423 0.3 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
DendriteCyan_1_1_R_2_2 DendriteCyan_1_11927 21.21 5.89 -24.95 42.57146 18.92818 -27.65476 0.44 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_12073 DendriteCyan_1_1_R_2_2 63.93293 31.96636 -30.35952 0.44 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
DendriteCyan_1_1_R_2_2_1__Extra_0 DendriteCyan_1_12073 55.96 27.1 -29.35 74.01923 41.23479 -32.13173 0.4203463 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_1_R_2_2_1__Extra_1 DendriteCyan_1_1_R_2_2_1__Extra_0 92.07848 55.36959 -34.91346 0.4203463 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_1_R_2_2_1 DendriteCyan_1_1_R_2_2_1__Extra_1 110.1377 69.50439 -37.69519 0.4203463 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_12167__Extra_0 DendriteCyan_1_1_R_2_2_1 128.1969 83.63918 -40.47692 0.3600706 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_12167__Extra_1 DendriteCyan_1_12167__Extra_0 146.2562 97.77398 -43.25865 0.3600706 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_12167 DendriteCyan_1_12167__Extra_1 164.3154 111.9088 -46.04038 0.3600706 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
DendriteCyan_1_1_R_2_2_2__Extra_0 DendriteCyan_1_12073 55.96 27.1 -29.35 81.04655 30.13041 -30.95674 0.4514068 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_1_R_2_2_2__Extra_1 DendriteCyan_1_1_R_2_2_2__Extra_0 106.1331 33.16082 -32.56348 0.4514068 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_1_R_2_2_2 DendriteCyan_1_1_R_2_2_2__Extra_1 131.2197 36.19122 -34.17022 0.4514068 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_12408__Extra_0 DendriteCyan_1_1_R_2_2_2 156.3062 39.22163 -35.77695 0.3834561 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_12408__Extra_1 DendriteCyan_1_12408__Extra_0 181.3928 42.25203 -37.38369 0.3834561 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_1_12408 DendriteCyan_1_12408__Extra_1 206.4793 45.28244 -38.99043 0.3834561 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
DendriteCyan_2_1_R Soma 6.88 -1.98 -50.5 18.10842 1.667235 -53.13374 0.4436557 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_2_12664 DendriteCyan_2_1_R 29.33683 5.31447 -55.76749 0.3480272 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
DendriteCyan_2_1_R_1__Extra_0 DendriteCyan_2_12664 23.72 3.49 -54.45 39.39822 13.94336 -53.05342 0.2899192 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_2_1_R_1__Extra_1 DendriteCyan_2_1_R_1__Extra_0 55.07643 24.39672 -51.65684 0.2899192 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_2_1_R_1 DendriteCyan_2_1_R_1__Extra_1 70.75465 34.85008 -50.26026 0.2899192 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_2_12709__Extra_0 DendriteCyan_2_1_R_1 86.43286 45.30344 -48.86367 0.2145833 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_2_12709__Extra_1 DendriteCyan_2_12709__Extra_0 102.1111 55.75681 -47.46709 0.2145833 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_2_12709 DendriteCyan_2_12709__Extra_1 117.7893 66.21017 -46.07051 0.2145833 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
DendriteCyan_2_1_R_2__Extra_0 DendriteCyan_2_12664 23.72 3.49 -54.45 42.81483 7.98403 -63.43167 0.2262385 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_2_1_R_2 DendriteCyan_2_1_R_2__Extra_0 61.90967 12.47806 -72.41334 0.2262385 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_2_12891__Extra_0 DendriteCyan_2_1_R_2 81.0045 16.97209 -81.395 0.2151679 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_2_12891 DendriteCyan_2_12891__Extra_0 100.0993 21.46612 -90.37668 0.2151679 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
DendriteCyan_3_1_R Soma 9.63 -14.99 -45.2 22.23314 -12.68199 -52.15901 0.5983382 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_3_13002 DendriteCyan_3_1_R 34.83629 -10.37398 -59.11801 0.4523481 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
DendriteCyan_3_1_R_1 DendriteCyan_3_13002 27.65 -11.69 -55.15 34.80441 -3.420197 -54.85788 0.3 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_3_13032 DendriteCyan_3_1_R_1 41.95883 4.849605 -54.56575 0.3 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
DendriteCyan_3_1_R_1_1__Extra_0 DendriteCyan_3_13032 41.12 3.88 -54.6 57.02499 10.99575 -58.87691 0.2463797 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_3_1_R_1_1__Extra_1 DendriteCyan_3_1_R_1_1__Extra_0 72.92999 18.11151 -63.15382 0.2463797 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_3_1_R_1_1 DendriteCyan_3_1_R_1_1__Extra_1 88.83498 25.22726 -67.43073 0.2463797 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_3_13069__Extra_0 DendriteCyan_3_1_R_1_1 104.74 32.34301 -71.70763 0.2078947 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_3_13069__Extra_1 DendriteCyan_3_13069__Extra_0 120.645 39.45877 -75.98454 0.2078947 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_3_13069 DendriteCyan_3_13069__Extra_1 136.55 46.57452 -80.26144 0.2078947 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
DendriteCyan_3_1_R_1_2__Extra_0 DendriteCyan_3_13032 41.12 3.88 -54.6 57.16552 16.16816 -60.37893 0.22 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_3_1_R_1_2__Extra_1 DendriteCyan_3_1_R_1_2__Extra_0 73.21105 28.45633 -66.15786 0.22 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_3_1_R_1_2 DendriteCyan_3_1_R_1_2__Extra_1 89.25658 40.74449 -71.93679 0.22 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_3_13250__Extra_0 DendriteCyan_3_1_R_1_2 105.3021 53.03265 -77.71571 0.22 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_3_13250__Extra_1 DendriteCyan_3_13250__Extra_0 121.3476 65.32082 -83.49464 0.22 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_3_13250 DendriteCyan_3_13250__Extra_1 137.3932 77.60898 -89.27357 0.22 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
DendriteCyan_3_1_R_2 DendriteCyan_3_13002 27.65 -11.69 -55.15 27.91019 -12.16035 -55.15 0.37 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_3_13457 DendriteCyan_3_1_R_2 28.17039 -12.63071 -55.15 0.37 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
DendriteCyan_3_1_R_2_1 DendriteCyan_3_13457 28.17 -12.63 -55.15 41.95237 -12.30009 -71.71308 0.3116423 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_3_13458 DendriteCyan_3_1_R_2_1 55.73474 -11.97017 -88.27617 0.2827021 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
DendriteCyan_3_1_R_2_2__Extra_0 DendriteCyan_3_13457 28.17 -12.63 -55.15 39.75101 -25.92683 -58.51981 0.3343798 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_3_1_R_2_2 DendriteCyan_3_1_R_2_2__Extra_0 51.33202 -39.22366 -61.88962 0.3343798 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_3_13493__Extra_0 DendriteCyan_3_1_R_2_2 62.91304 -52.5205 -65.25943 0.2818325 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
DendriteCyan_3_13493 DendriteCyan_3_13493__Extra_0 74.49405 -65.81733 -68.62924 0.2818325 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R Soma -27.68 -27.47 -18.65 -30.0488 -28.88826 -18.65 2 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_13600 ApicalCyan_1_R -32.41759 -30.30652 -18.65 2 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_1 ApicalCyan_13600 -32.39 -30.29 -18.65 -31.91343 -47.59313 -18.03901 0.3695268 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_13606 ApicalCyan_1_R_1 -31.43686 -64.89627 -17.42803 0.3000483 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_1_1__Extra_0 ApicalCyan_13606 -31.61 -58.61 -17.65 -48.07948 -74.92531 -14.99486 0.2382382 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_1_1__Extra_1 ApicalCyan_1_R_1_1__Extra_0 -64.54897 -91.24063 -12.33972 0.2382382 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_1_1 ApicalCyan_1_R_1_1__Extra_1 -81.01845 -107.5559 -9.684578 0.2382382 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_13666__Extra_0 ApicalCyan_1_R_1_1 -97.48793 -123.8713 -7.029438 0.2096968 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_13666__Extra_1 ApicalCyan_13666__Extra_0 -113.9574 -140.1866 -4.374297 0.2096968 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_13666 ApicalCyan_13666__Extra_1 -130.4269 -156.5019 -1.719157 0.2096968 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_1_2 ApicalCyan_13606 -31.61 -58.61 -17.65 -30.16769 -64.17979 -17.65 0.2544372 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_13945 ApicalCyan_1_R_1_2 -28.72537 -69.74957 -17.65 0.2087205 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_1_2_1 ApicalCyan_13945 -28.79 -69.5 -17.65 -15.146 -87.17631 -13.67361 0.22 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_13967 ApicalCyan_1_R_1_2_1 -1.501999 -104.8526 -9.697213 0.22 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_1_2_2__Extra_0 ApicalCyan_13945 -28.79 -69.5 -17.65 -31.77508 -83.00572 -16.97952 0.22 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_1_2_2 ApicalCyan_1_R_1_2_2__Extra_0 -34.76015 -96.51144 -16.30905 0.22 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_14049__Extra_0 ApicalCyan_1_R_1_2_2 -37.74523 -110.0172 -15.63857 0.22 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_14049 ApicalCyan_14049__Extra_0 -40.7303 -123.5229 -14.9681 0.22 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2 ApicalCyan_13600 -32.39 -30.29 -18.65 -32.99586 -30.48132 -18.19827 2.07 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_14178 ApicalCyan_1_R_2 -33.60171 -30.67265 -17.74653 2.07 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1 ApicalCyan_14178 -33.53 -30.65 -17.8 -34.21 -30.9 -17.8 2.07 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_1__Extra_0 ApicalCyan_1_R_2_1 -38.08797 -50.41988 -15.36414 0.3373753 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_1__Extra_1 ApicalCyan_1_R_2_1_1__Extra_0 -41.96594 -69.93977 -12.92828 0.3373753 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_1 ApicalCyan_1_R_2_1_1__Extra_1 -45.84391 -89.45966 -10.49242 0.3373753 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_14179__Extra_0 ApicalCyan_1_R_2_1_1 -49.72187 -108.9795 -8.056555 0.2463721 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_14179__Extra_1 ApicalCyan_14179__Extra_0 -53.59985 -128.4994 -5.620694 0.2463721 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_14179 ApicalCyan_14179__Extra_1 -57.47781 -148.0193 -3.184833 0.2463721 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2 ApicalCyan_1_R_2_1 -34.62334 -31.20687 -17.8 2.07 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_14412 ApicalCyan_1_R_2_1_2 -35.03668 -31.51375 -17.8 2.07 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1 ApicalCyan_14412 -34.87 -31.39 -17.8 -43.64271 -35.80506 -19.75204 1.905998 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_14413 ApicalCyan_1_R_2_1_2_1 -52.41541 -40.22012 -21.70408 1.670498 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_1 ApicalCyan_14413 -50.15 -39.08 -21.2 -50.4174 -38.10477 -21.2 0.44 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_14438 ApicalCyan_1_R_2_1_2_1_1 -50.68481 -37.12953 -21.2 0.44 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_1_1__Extra_0 ApicalCyan_14438 -50.66 -37.22 -21.2 -73.39478 -42.56329 -22.62528 0.3101669 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_1_1 ApicalCyan_1_R_2_1_2_1_1_1__Extra_0 -96.12956 -47.90659 -24.05057 0.3101669 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_14441__Extra_0 ApicalCyan_1_R_2_1_2_1_1_1 -118.8643 -53.24989 -25.47585 0.228801 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_14441 ApicalCyan_14441__Extra_0 -141.5991 -58.59318 -26.90113 0.228801 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_1_2__Extra_0 ApicalCyan_14438 -50.66 -37.22 -21.2 -69.93454 -25.33409 -32.13068 0.3989904 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_1_2 ApicalCyan_1_R_2_1_2_1_1_2__Extra_0 -89.20908 -13.44817 -43.06136 0.3989904 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_14603__Extra_0 ApicalCyan_1_R_2_1_2_1_1_2 -108.4836 -1.56226 -53.99204 0.3029598 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_14603 ApicalCyan_14603__Extra_0 -127.7582 10.32365 -64.92272 0.3029598 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2 ApicalCyan_14413 -50.15 -39.08 -21.2 -50.58366 -39.84432 -21.2 1.7 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_14775 ApicalCyan_1_R_2_1_2_1_2 -51.01731 -40.60865 -21.2 1.7 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1 ApicalCyan_14775 -50.95 -40.49 -21.2 -53.63693 -44.49763 -22.70856 1.708805 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_14779 ApicalCyan_1_R_2_1_2_1_2_1 -56.32387 -48.50526 -24.21711 1.445393 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_1 ApicalCyan_14779 -55.67 -47.53 -23.85 -63.04387 -45.83372 -22.77161 0.37 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_14792 ApicalCyan_1_R_2_1_2_1_2_1_1 -70.41774 -44.13744 -21.69322 0.37 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_1_1__Extra_0 ApicalCyan_14792 -68.32 -44.62 -22 -81.14507 -54.58161 -14.11877 0.22 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_1_1 ApicalCyan_1_R_2_1_2_1_2_1_1_1__Extra_0 -93.97014 -64.54322 -6.237534 0.22 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_14818__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_1_1 -106.7952 -74.50484 1.6437 0.22 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_14818 ApicalCyan_14818__Extra_0 -119.6203 -84.46645 9.524933 0.22 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_1_2 ApicalCyan_14792 -68.32 -44.62 -22 -71.47556 -45.29993 -23.71434 0.37 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_14937 ApicalCyan_1_R_2_1_2_1_2_1_1_2 -74.6311 -45.97985 -25.42869 0.37 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_1_2_1__Extra_0 ApicalCyan_14937 -73.75 -45.79 -24.95 -89.20978 -25.83726 -25.73502 0.3188744 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_1_2_1 ApicalCyan_1_R_2_1_2_1_2_1_1_2_1__Extra_0 -104.6696 -5.884525 -26.52003 0.3188744 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_14948__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_1_2_1 -120.1293 14.06821 -27.30504 0.2432081 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_14948 ApicalCyan_14948__Extra_0 -135.5891 34.02095 -28.09006 0.2432081 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_1_2_2__Extra_0 ApicalCyan_14937 -73.75 -45.79 -24.95 -94.18682 -43.98085 -30.38589 0.3189326 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_1_2_2__Extra_1 ApicalCyan_1_R_2_1_2_1_2_1_1_2_2__Extra_0 -114.6236 -42.1717 -35.82177 0.3189326 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_1_2_2 ApicalCyan_1_R_2_1_2_1_2_1_1_2_2__Extra_1 -135.0605 -40.36256 -41.25766 0.3189326 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_15190__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_1_2_2 -155.4973 -38.55341 -46.69355 0.243417 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_15190__Extra_1 ApicalCyan_15190__Extra_0 -175.9341 -36.74426 -52.12944 0.243417 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_15190 ApicalCyan_15190__Extra_1 -196.3709 -34.93512 -57.56532 0.243417 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2 ApicalCyan_14779 -55.67 -47.53 -23.85 -57.55142 -48.79658 -25.0182 1.41 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_15427 ApicalCyan_1_R_2_1_2_1_2_1_2 -59.43284 -50.06315 -26.1864 1.41 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1 ApicalCyan_15427 -58.73 -49.59 -25.75 -62.24148 -54.40078 -28.13019 1.389953 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_15435 ApicalCyan_1_R_2_1_2_1_2_1_2_1 -65.75295 -59.21156 -30.51038 1.252214 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_1 ApicalCyan_15435 -65 -58.18 -30 -69.05708 -56.56788 -30.23795 0.3 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_15451 ApicalCyan_1_R_2_1_2_1_2_1_2_1_1 -73.11416 -54.95575 -30.4759 0.3 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2 ApicalCyan_15435 -65 -58.18 -30 -65.11818 -59.2082 -30.35455 1.26 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_15471 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2 -65.23637 -60.2364 -30.7091 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1 ApicalCyan_15471 -65.2 -59.92 -30.6 -65.3978 -64.55058 -30.80287 1.26 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_15472 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1 -65.5956 -69.18115 -31.00574 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_1 ApicalCyan_15472 -65.59 -69.05 -31 -66.66283 -70.12284 -31 0.52 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_15488 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_1 -67.73568 -71.19568 -31 0.52 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_1_1 ApicalCyan_15488 -67.66 -71.12 -31 -68.58801 -83.23914 -42.68606 0.37 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_15493 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_1_1 -69.51602 -95.35827 -54.37212 0.37 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_1_1_1 ApicalCyan_15493 -69.01 -88.75 -48 -74.07208 -96.9435 -56.71148 0.3 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_15535 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_1_1_1 -79.13416 -105.137 -65.42297 0.3 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_1_1_2 ApicalCyan_15493 -69.01 -88.75 -48 -47.37137 -97.89514 -56.50235 0.3789647 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_15562 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_1_1_2 -25.73274 -107.0403 -65.0047 0.243623 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_1_2__Extra_0 ApicalCyan_15488 -67.66 -71.12 -31 -78.77588 -77.90154 -41.74252 0.3934966 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_1_2 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_1_2__Extra_0 -89.89175 -84.68307 -52.48504 0.3934966 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_15640__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_1_2 -101.0076 -91.4646 -63.22756 0.3584352 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_15640 ApicalCyan_15640__Extra_0 -112.1235 -98.24612 -73.97008 0.3584352 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2 ApicalCyan_15472 -65.59 -69.05 -31 -65.58415 -70.6401 -30.41541 1.26 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_15740 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2 -65.57831 -72.23019 -29.83081 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1 ApicalCyan_15740 -65.58 -71.77 -30 -71.50235 -80.85587 -27.63448 1.26 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_15744 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1 -77.4247 -89.94175 -25.26896 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_1__Extra_0 ApicalCyan_15744 -75.97 -87.71 -25.85 -49.7147 -94.66214 -33.35017 0.4287294 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_1 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_1__Extra_0 -23.4594 -101.6143 -40.85035 0.4287294 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_15796__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_1 2.795906 -108.5664 -48.35052 0.3618173 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_15796 ApicalCyan_15796__Extra_0 29.05121 -115.5186 -55.85069 0.3618173 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2 ApicalCyan_15744 -75.97 -87.71 -25.85 -76.46111 -88.31484 -25.85 1.26 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_16010 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2 -76.95222 -88.91969 -25.85 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1 ApicalCyan_16010 -76.92 -88.88 -25.85 -81.04023 -94.9101 -21.14211 1.26 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_16012 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1 -85.16047 -100.9402 -16.43423 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1 ApicalCyan_16012 -83.09 -97.91 -18.8 -104.3935 -106.4301 -14.15497 0.37 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_16030 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1 -125.697 -114.9503 -9.509939 0.37 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1 ApicalCyan_16030 -116.57 -111.3 -11.5 -135.1485 -110.7812 -6.651541 0.3296592 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_16121 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1 -153.7271 -110.2624 -1.803082 0.2881791 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2 ApicalCyan_16030 -116.57 -111.3 -11.5 -135.0055 -124.0282 -7.257274 0.3 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_16199 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2 -153.441 -136.7563 -3.014547 0.3 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2 ApicalCyan_16012 -83.09 -97.91 -18.8 -83.65777 -99.39974 -18.8 1.26 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_16303 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2 -84.22554 -100.8895 -18.8 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1 ApicalCyan_16303 -84.18 -100.77 -18.8 -84.61435 -101.9631 -18.8 1.26 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_16310 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1 -85.04869 -103.1563 -18.8 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1 ApicalCyan_16310 -85.01 -103.05 -18.8 -79.32005 -108.7337 -18.76874 0.52 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_16313 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1 -73.6301 -114.4174 -18.73747 0.52 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1 ApicalCyan_16313 -75.91 -112.14 -18.75 -74.59409 -115.3288 -19.63748 0.37 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_16347 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1 -73.27816 -118.5176 -20.52496 0.37 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1_1__Extra_0 ApicalCyan_16347 -73.76 -117.35 -20.2 -56.45424 -117.7522 -30.87574 0.3160917 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1_1 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1_1__Extra_0 -39.14848 -118.1544 -41.55148 0.3160917 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_16362__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1_1 -21.84272 -118.5567 -52.22721 0.2751244 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_16362 ApicalCyan_16362__Extra_0 -4.536964 -118.9589 -62.90295 0.2751244 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1_2__Extra_0 ApicalCyan_16347 -73.76 -117.35 -20.2 -84.27458 -137.8859 -17.94666 0.2666331 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1_2 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1_2__Extra_0 -94.78917 -158.4217 -15.69332 0.2666331 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_16501__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1_2 -105.3038 -178.9576 -13.43997 0.2042267 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_16501 ApicalCyan_16501__Extra_0 -115.8183 -199.4935 -11.18663 0.2042267 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2 ApicalCyan_16313 -75.91 -112.14 -18.75 -69.38297 -127.355 -6.548579 0.4646997 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_16705 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2 -62.85595 -142.57 5.652842 0.3931834 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2 ApicalCyan_16310 -85.01 -103.05 -18.8 -85.04005 -103.766 -18.8 1.26 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_16770 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2 -85.07008 -104.4821 -18.8 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1 ApicalCyan_16770 -85.07 -104.48 -18.8 -88.88457 -108.7258 -18.77433 1.26 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_16772 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1 -92.69914 -112.9716 -18.74866 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1 ApicalCyan_16772 -92.5 -112.75 -18.75 -81.11728 -116.9604 -16.99013 0.44 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_16798 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1 -69.73456 -121.1708 -15.23026 0.44 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1 ApicalCyan_16798 -75.36 -119.09 -16.1 -54.41058 -119.7497 -8.693035 0.3884651 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_16842 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1 -33.46117 -120.4095 -1.286069 0.3596758 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2 ApicalCyan_16798 -75.36 -119.09 -16.1 -76.76497 -141.6929 -8.252174 0.37 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_16901 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2 -78.16993 -164.2958 -0.4043484 0.37 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2 ApicalCyan_16772 -92.5 -112.75 -18.75 -93.13483 -113.0623 -18.75 1.26 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_16984 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2 -93.76966 -113.3746 -18.75 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1 ApicalCyan_16984 -93.74 -113.36 -18.75 -105.6616 -121.0913 -20.46867 1.26 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_16986 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1 -117.5831 -128.8226 -22.18734 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1 ApicalCyan_16986 -115.59 -127.53 -21.9 -115.8741 -127.3298 -21.93229 1.26 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_17029 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1 -116.1582 -127.1297 -21.96457 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1 ApicalCyan_17029 -116.03 -127.22 -21.95 -115.0581 -128.7856 -21.95 0.59 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_17030 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1 -114.0861 -130.3512 -21.95 0.59 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1_1 ApicalCyan_17030 -114.18 -130.2 -21.95 -128.1232 -138.2137 -30.12206 0.4539861 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_17034 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1_1 -142.0663 -146.2274 -38.29411 0.3913982 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1_1_1__Extra_0 ApicalCyan_17034 -136.19 -142.85 -34.85 -155.872 -159.646 -33.6832 0.3469933 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1_1_1 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1_1_1__Extra_0 -175.554 -176.442 -32.5164 0.3469933 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_17090__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1_1_1 -195.236 -193.2381 -31.3496 0.2896118 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_17090 ApicalCyan_17090__Extra_0 -214.918 -210.0341 -30.1828 0.2896118 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1_1_2 ApicalCyan_17034 -136.19 -142.85 -34.85 -154.5611 -147.3625 -47.75194 0.3824965 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_17359 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1_1_2 -172.9322 -151.8751 -60.65387 0.315272 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1_2 ApicalCyan_17030 -114.18 -130.2 -21.95 -105.4752 -137.0241 -29.3945 0.5012746 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_17436 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1_2 -96.77032 -143.8482 -36.83899 0.4306264 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1_2_1 ApicalCyan_17436 -100.85 -140.65 -33.35 -89.46406 -149.3963 -45.52118 0.421019 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_17461 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1_2_1 -78.07812 -158.1427 -57.69236 0.3609643 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1_2_2__Extra_0 ApicalCyan_17436 -100.85 -140.65 -33.35 -82.15337 -134.5558 -38.52743 0.4304233 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1_2_2 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1_2_2__Extra_0 -63.45675 -128.4617 -43.70486 0.4304233 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_17496__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_1_2_2 -44.76012 -122.3676 -48.8823 0.3641874 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_17496 ApicalCyan_17496__Extra_0 -26.06349 -116.2734 -54.05973 0.3641874 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2 ApicalCyan_17029 -116.03 -127.22 -21.95 -116.2658 -128.1934 -21.95 1.26 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_17658 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2 -116.5016 -129.1667 -21.95 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1 ApicalCyan_17658 -116.42 -128.83 -21.95 -124.252 -140.3453 -22.91404 1.26 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_17661 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1 -132.084 -151.8607 -23.87809 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1 ApicalCyan_17661 -128.2 -146.15 -23.4 -129.15 -146.64 -23.4 1.26 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_1 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1 -129.6125 -148.7497 -23.4 0.67 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_17705 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_1 -130.0749 -150.8593 -23.4 0.67 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_1_1 ApicalCyan_17705 -130.04 -150.7 -23.4 -143.0704 -174.6908 -18.603 0.3399848 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_17714 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_1_1 -156.1008 -198.6817 -13.80599 0.2884386 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_1_2 ApicalCyan_17705 -130.04 -150.7 -23.4 -134.2981 -155.8519 -21.10176 0.52 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_17847 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_1_2 -138.5563 -161.0038 -18.80351 0.52 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_1_2_1__Extra_0 ApicalCyan_17847 -136.71 -158.77 -19.8 -139.8849 -181.0192 -16.19845 0.428738 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_1_2_1 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_1_2_1__Extra_0 -143.0598 -203.2684 -12.59691 0.428738 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_17874__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_1_2_1 -146.2348 -225.5176 -8.995361 0.3224692 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_17874 ApicalCyan_17874__Extra_0 -149.4097 -247.7668 -5.393815 0.3224692 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_1_2_2 ApicalCyan_17847 -136.71 -158.77 -19.8 -137.9427 -187.4246 -15.27559 0.4524294 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_18058 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_1_2_2 -139.1755 -216.0791 -10.75119 0.3858559 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1 -129.7635 -147.1119 -20.77508 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_18187 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2 -130.3769 -147.5838 -18.15017 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1 ApicalCyan_18187 -130.19 -147.44 -18.95 -132.5752 -149.3925 -18.92361 1.26 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_18188 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1 -134.9604 -151.345 -18.89723 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_1 ApicalCyan_18188 -134.71 -151.14 -18.9 -149.4043 -160.8769 -15.56327 0.37 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_18198 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_1 -164.0987 -170.6138 -12.22653 0.37 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_1_1 ApicalCyan_18198 -157.83 -166.46 -13.65 -173.9196 -183.2045 -9.101503 0.3 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_18287 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_1_1 -190.0091 -199.9491 -4.553007 0.3 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_1_2 ApicalCyan_18198 -157.83 -166.46 -13.65 -164.0045 -168.0793 -13.62199 0.37 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_18393 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_1_2 -170.179 -169.6985 -13.59397 0.37 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_1_2_1 ApicalCyan_18393 -168.85 -169.35 -13.6 -185.3487 -164.5967 -7.830793 0.37 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_18423 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_1_2_1 -201.8474 -159.8434 -2.061586 0.37 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_1_2_2__Extra_0 ApicalCyan_18393 -168.85 -169.35 -13.6 -197.9376 -175.1544 -14.80986 0.3971377 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_1_2_2 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_1_2_2__Extra_0 -227.0251 -180.9587 -16.01973 0.3971377 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_18493__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_1_2_2 -256.1126 -186.7631 -17.2296 0.3235303 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_18493 ApicalCyan_18493__Extra_0 -285.2002 -192.5675 -18.43946 0.3235303 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2 ApicalCyan_18188 -134.71 -151.14 -18.9 -135.7427 -152.1451 -19.36943 1.26 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_18746 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2 -136.7755 -153.1503 -19.83885 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1 ApicalCyan_18746 -136.58 -152.96 -19.75 -147.37 -173.2321 -23.68573 1.26 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_18749 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1 -158.1599 -193.5041 -27.62146 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_1 ApicalCyan_18749 -154.4 -186.44 -26.25 -157.3074 -187.1253 -26.22404 0.59 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_18810 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_1 -160.2147 -187.8106 -26.19808 0.59 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_1_1__Extra_0 ApicalCyan_18810 -160 -187.76 -26.2 -183.6249 -188.8236 -25.31368 0.3975528 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_1_1 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_1_1__Extra_0 -207.2498 -189.8872 -24.42737 0.3975528 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_18821__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_1_1 -230.8747 -190.9507 -23.54105 0.2815993 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_18821 ApicalCyan_18821__Extra_0 -254.4996 -192.0143 -22.65474 0.2815993 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_1_2 ApicalCyan_18810 -160 -187.76 -26.2 -162.2539 -189.4109 -24.73641 0.44 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_19017 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_1_2 -164.5079 -191.0619 -23.27283 0.44 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_1_2_1 ApicalCyan_19017 -163.85 -190.58 -23.7 -184.8007 -205.624 -13.60435 0.3855758 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_19028 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_1_2_1 -205.7514 -220.668 -3.508709 0.3406231 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_1_2_2__Extra_0 ApicalCyan_19017 -163.85 -190.58 -23.7 -188.0945 -199.4932 -33.04151 0.37 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_1_2_2 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_1_2_2__Extra_0 -212.3389 -208.4064 -42.38301 0.37 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_19140__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_1_2_2 -236.5834 -217.3197 -51.72452 0.37 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_19140 ApicalCyan_19140__Extra_0 -260.8279 -226.2329 -61.06603 0.37 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2 ApicalCyan_18749 -154.4 -186.44 -26.25 -154.6001 -187.0002 -26.25 1.26 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_19376 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2 -154.8002 -187.5605 -26.25 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1 ApicalCyan_19376 -154.8 -187.56 -26.25 -168.0937 -199.4569 -28.02565 1.26 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_19377 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1 -181.3874 -211.3537 -29.8013 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_1__Extra_0 ApicalCyan_19377 -177.26 -207.66 -29.25 -198.8065 -209.691 -38.69029 0.3515698 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_1 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_1__Extra_0 -220.3529 -211.722 -48.13058 0.3515698 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_19434__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_1 -241.8994 -213.753 -57.57087 0.2893216 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_19434 ApicalCyan_19434__Extra_0 -263.4458 -215.784 -67.01115 0.2893216 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2 ApicalCyan_19377 -177.26 -207.66 -29.25 -177.409 -208.5128 -29.25 1.26 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_19602 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2 -177.558 -209.3655 -29.25 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_1__Extra_0 ApicalCyan_19602 -177.55 -209.32 -29.25 -172.5548 -230.6592 -33.9577 0.3167413 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_1 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_1__Extra_0 -167.5596 -251.9983 -38.66539 0.3167413 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_19605__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_1 -162.5644 -273.3375 -43.37309 0.2384119 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_19605 ApicalCyan_19605__Extra_0 -157.5692 -294.6766 -48.08078 0.2384119 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2 ApicalCyan_19602 -177.55 -209.32 -29.25 -178.55 -210.42 -29.25 1.26 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_1__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2 -176.4293 -225.1324 -36.70229 0.3 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_1 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_1__Extra_0 -174.3087 -239.8447 -44.15457 0.3 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_19753__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_1 -172.188 -254.5571 -51.60686 0.3 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_19753 ApicalCyan_19753__Extra_0 -170.0673 -269.2694 -59.05914 0.3 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2 -181.2469 -214.9544 -28.91545 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_19878 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2 -183.9439 -219.4888 -28.58091 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_1 ApicalCyan_19878 -183.79 -219.23 -28.6 -182.0137 -230.7325 -44.77921 0.4718404 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_19893 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_1 -180.2374 -242.2349 -60.95842 0.3475719 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2 ApicalCyan_19878 -183.79 -219.23 -28.6 -186.2624 -221.7487 -28.6 1.26 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_19927 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2 -188.7348 -224.2673 -28.6 1.26 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1 ApicalCyan_19927 -188.6 -224.13 -28.6 -222.0115 -236.2366 -29.47925 0.9306052 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_19942 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1 -255.4229 -248.3432 -30.3585 0.8645472 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_1 ApicalCyan_19942 -238 -242.03 -29.9 -246.735 -259.8337 -24.09164 0.6167191 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_20056 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_1 -255.47 -277.6375 -18.28327 0.5253305 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_1_1 ApicalCyan_20056 -251.61 -269.77 -20.85 -262.136 -272.3593 -15.94034 0.37 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_20120 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_1_1 -272.6621 -274.9486 -11.03068 0.37 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_1_1_1__Extra_0 ApicalCyan_20120 -268.44 -273.91 -13 -295.6263 -276.4443 -12.11981 0.3571666 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_1_1_1 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_1_1_1__Extra_0 -322.8127 -278.9786 -11.23961 0.3571666 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_20168__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_1_1_1 -349.999 -281.5129 -10.35942 0.2928949 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_20168 ApicalCyan_20168__Extra_0 -377.1854 -284.0472 -9.479229 0.2928949 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_1_1_2__Extra_0 ApicalCyan_20120 -268.44 -273.91 -13 -285.2779 -286.9393 -17.27343 0.2950563 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_1_1_2__Extra_1 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_1_1_2__Extra_0 -302.1157 -299.9686 -21.54686 0.2950563 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_1_1_2__Extra_2 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_1_1_2__Extra_1 -318.9536 -312.9979 -25.82029 0.2950563 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_1_1_2__Extra_3 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_1_1_2__Extra_2 -335.7914 -326.0271 -30.09373 0.2950563 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_1_1_2 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_1_1_2__Extra_3 -352.6293 -339.0564 -34.36716 0.2950563 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_20329__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_1_1_2 -369.4671 -352.0857 -38.64059 0.1947354 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_20329__Extra_1 ApicalCyan_20329__Extra_0 -386.305 -365.115 -42.91402 0.1947354 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_20329__Extra_2 ApicalCyan_20329__Extra_1 -403.1428 -378.1442 -47.18745 0.1947354 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_20329__Extra_3 ApicalCyan_20329__Extra_2 -419.9807 -391.1735 -51.46088 0.1947354 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_20329 ApicalCyan_20329__Extra_3 -436.8185 -404.2028 -55.73431 0.1947354 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_1_2__Extra_0 ApicalCyan_20056 -251.61 -269.77 -20.85 -265.3531 -284.7755 -31.5745 0.4338454 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_1_2__Extra_1 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_1_2__Extra_0 -279.0962 -299.7811 -42.29901 0.4338454 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_1_2 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_1_2__Extra_1 -292.8393 -314.7867 -53.02351 0.4338454 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_20748__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_1_2 -306.5823 -329.7922 -63.74801 0.241357 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_20748__Extra_1 ApicalCyan_20748__Extra_0 -320.3254 -344.7978 -74.47251 0.241357 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_20748 ApicalCyan_20748__Extra_1 -334.0685 -359.8034 -85.19701 0.241357 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_2 ApicalCyan_19942 -238 -242.03 -29.9 -253.1778 -246.4805 -28.82412 0.7731275 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_21030 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_2 -268.3556 -250.9309 -27.74824 0.7270926 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_2_1__Extra_0 ApicalCyan_21030 -266.92 -250.51 -27.85 -288.7569 -247.1322 -40.11019 0.4092655 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_2_1 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_2_1__Extra_0 -310.5938 -243.7544 -52.37038 0.4092655 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_21096__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_2_1 -332.4307 -240.3766 -64.63057 0.3531598 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_21096 ApicalCyan_21096__Extra_0 -354.2676 -236.9988 -76.89076 0.3531598 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_2_2 ApicalCyan_21030 -266.92 -250.51 -27.85 -279.8619 -258.2607 -28.84368 0.737968 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_21278 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_2_2 -292.8037 -266.0114 -29.83735 0.6690586 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_2_2_1__Extra_0 ApicalCyan_21278 -288.41 -263.38 -29.5 -316.9256 -274.4045 -27.24405 0.4696771 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_2_2_1__Extra_1 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_2_2_1__Extra_0 -345.4412 -285.4291 -24.98809 0.4696771 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_2_2_1__Extra_2 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_2_2_1__Extra_1 -373.9568 -296.4536 -22.73214 0.4696771 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_2_2_1 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_2_2_1__Extra_2 -402.4724 -307.4781 -20.47618 0.4696771 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_21336__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_2_2_1 -430.988 -318.5027 -18.22023 0.2968993 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_21336__Extra_1 ApicalCyan_21336__Extra_0 -459.5035 -329.5272 -15.96427 0.2968993 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_21336__Extra_2 ApicalCyan_21336__Extra_1 -488.0192 -340.5518 -13.70832 0.2968993 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_21336 ApicalCyan_21336__Extra_2 -516.5347 -351.5763 -11.45236 0.2968993 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_2_2_2__Extra_0 ApicalCyan_21278 -288.41 -263.38 -29.5 -313.0813 -280.1125 -27.23452 0.5111436 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_2_2_2__Extra_1 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_2_2_2__Extra_0 -337.7526 -296.8449 -24.96903 0.5111436 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_2_2_2__Extra_2 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_2_2_2__Extra_1 -362.4239 -313.5774 -22.70354 0.5111436 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_2_2_2 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_2_2_2__Extra_2 -387.0952 -330.3098 -20.43806 0.5111436 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_21855__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_1_2_2_2 -411.7664 -347.0423 -18.17257 0.3715453 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_21855__Extra_1 ApicalCyan_21855__Extra_0 -436.4377 -363.7747 -15.90709 0.3715453 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_21855__Extra_2 ApicalCyan_21855__Extra_1 -461.1091 -380.5072 -13.6416 0.3715453 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_21855 ApicalCyan_21855__Extra_2 -485.7803 -397.2396 -11.37612 0.3715453 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2 ApicalCyan_19927 -188.6 -224.13 -28.6 -194.5052 -237.2349 -27.66312 1.11 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_22283 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2 -200.4103 -250.3398 -26.72625 1.11 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_1 ApicalCyan_22283 -199 -247.21 -26.95 -184.4596 -272.071 -39.56931 0.4152517 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_22343 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_1 -169.9193 -296.9321 -52.18863 0.3134667 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2 ApicalCyan_22283 -199 -247.21 -26.95 -199.9752 -250.0937 -28.11663 1.11 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_22452 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2 -200.9504 -252.9773 -29.28325 1.11 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_1__Extra_0 ApicalCyan_22452 -200.63 -252.03 -28.9 -200.7616 -269.7618 -22.00125 0.52 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_1 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_1__Extra_0 -200.8931 -287.4936 -15.1025 0.52 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_22465__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_1 -201.0247 -305.2253 -8.203746 0.52 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_22465 ApicalCyan_22465__Extra_0 -201.1562 -322.9571 -1.304995 0.52 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2 ApicalCyan_22452 -200.63 -252.03 -28.9 -216.5059 -268.2413 -20.51366 0.9386857 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_22557 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2 -232.3817 -284.4526 -12.12731 0.8788512 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_1 ApicalCyan_22557 -223.82 -275.71 -16.65 -240.5153 -291.242 -12.15976 0.6000654 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_22647 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_1 -257.2105 -306.774 -7.669525 0.501448 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_1_1__Extra_0 ApicalCyan_22647 -251.52 -301.48 -9.2 -268.9213 -298.7847 -20.50721 0.3661193 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_1_1__Extra_1 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_1_1__Extra_0 -286.3225 -296.0894 -31.81443 0.3661193 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_1_1 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_1_1__Extra_1 -303.7238 -293.394 -43.12164 0.3661193 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_22736__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_1_1 -321.1251 -290.6987 -54.42885 0.2598607 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_22736__Extra_1 ApicalCyan_22736__Extra_0 -338.5264 -288.0034 -65.73606 0.2598607 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_22736 ApicalCyan_22736__Extra_1 -355.9276 -285.308 -77.04327 0.2598607 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_1_2 ApicalCyan_22647 -251.52 -301.48 -9.2 -263.8791 -308.2363 -5.474368 0.52 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_22901 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_1_2 -276.2381 -314.9926 -1.748737 0.52 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_2 ApicalCyan_22557 -223.82 -275.71 -16.65 -246.4706 -271.1034 -24.51565 0.8018005 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_22958 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_2 -269.1211 -266.4968 -32.3813 0.6675029 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_2_1__Extra_0 ApicalCyan_22958 -259.96 -268.36 -29.2 -283.8731 -278.8466 -31.63499 0.3839949 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_2_1__Extra_1 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_2_1__Extra_0 -307.7863 -289.3332 -34.06997 0.3839949 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_2_1__Extra_2 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_2_1__Extra_1 -331.6994 -299.8198 -36.50496 0.3839949 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_2_1__Extra_3 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_2_1__Extra_2 -355.6125 -310.3064 -38.93995 0.3839949 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_2_1 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_2_1__Extra_3 -379.5256 -320.793 -41.37493 0.3839949 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_23050__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_2_1 -403.4387 -331.2796 -43.80992 0.3060293 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_23050__Extra_1 ApicalCyan_23050__Extra_0 -427.3519 -341.7662 -46.2449 0.3060293 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_23050__Extra_2 ApicalCyan_23050__Extra_1 -451.265 -352.2527 -48.67989 0.3060293 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_23050__Extra_3 ApicalCyan_23050__Extra_2 -475.1781 -362.7394 -51.11488 0.3060293 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_23050 ApicalCyan_23050__Extra_3 -499.0912 -373.226 -53.54986 0.3060293 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
*double_endpoint
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_2_2__Extra_0 ApicalCyan_22958 -259.96 -268.36 -29.2 -290.714 -265.6001 -39.00208 0.4642183 
*double_endpoint_off

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_2_2 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_2_2__Extra_0 -321.468 -262.8402 -48.80417 0.4642183 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_23576__Extra_0 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_2_2_2_2_2_2_2 -352.2221 -260.0803 -58.60625 0.3444246 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_23576 ApicalCyan_23576__Extra_0 -382.9761 -257.3204 -68.40833 0.3444246 

// Cell mechanism: LeakConductance (density: 3.0E-9 mS um^-2)
ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2_3 ApicalCyan_1_R_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_2_1_1_2_1_1_2_1_2_1_2_1_2_2 -178.15 -210.51 -30.8 1.26 

